spring.application.name=constructora-api

spring.datasource.url=jdbc:postgresql://localhost:5432/isanorte_db
spring.datasource.username=isanorte_user
spring.datasource.password=Nil71232516

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
